name: lexichron
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - pip
  - cython>=3.0
  - enchant
  - gxx_linux-64  # Linux only; omit or replace on macOS/Windows

  - pip:
      - -e .[notebook,linux]
