[project]
name = "ngram-prep"
version = "0.1.0"
description = "Download and prepare Google Books n-grams for ML/analysis."
readme = "README.md"
requires-python = ">=3.9"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
